sudo: required
language: generic
services:
     - docker

before_install:
    - docker build -t rajamecs/docker-react -f Dockerfile.dev .     

script:
    - docker run rajamecs/docker-react npm run test -- --coverage